services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FOLDER=/config
      - API_SERVER_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - /dockerfrenzy/config:/config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
