services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE_PATH=config.yaml
      - API_SERVER_PORT=8080
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
