services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE_PATH=config.yaml
      - API_SERVER_PORT=8080
      - EXEC_SERVER_URL=http://exec_server:3001
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    
  exec_server:
    depends_on:
      - api_server
    build:
      context: ./exec_server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=3001
      - SERVER_DOMAIN=localhost
      - API_SERVER_URL=http://api_server:8080
    ports:
      - 3001:3001

